name: Build, Test, Deploy - Site

on:
  push:
    paths:
      - site/**
      - .github/workflows/tbd-site.yml
  pull_request:
    paths:
      - site/**
      - .github/workflows/tbd-site.yml
  workflow_dispatch:

jobs:
  #########################
  ## Site Testing & Building
  #########################
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node and PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        working-directory: site
        run: pnpm install
      - name: Test and Build
        working-directory: site
        run: pnpm t
        env: 
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_WEBHOOK_SECRET: ${{ secrets.SANITY_WEBHOOK_SECRET }}
      - name: Upload search build
        # Switch to 'refs/heads/main' when merged
        if: github.ref == 'refs/heads/refactor/the-great-cms-migration'
        uses: actions/upload-artifact@v4
        with:
          name: search
          path: |
            ./site/public/pagefind
            ./site/.generated

  #########################
  ## Preview Deploy
  #########################
  preview:
    needs: test-build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download compiled site
        uses: actions/download-artifact@v1
        with:
          name: site
          path: public
      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SANITY_WEBHOOK_SECRET: ${{ secrets.SANITY_WEBHOOK_SECRET }}
          envkey_GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Deploy Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CROS_STAGING }}'
          expires: 30d

  #########################
  ## Production Deploy
  #########################
  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    # Change to 'refs/heads/main' when merged
    if: github.ref == 'refs/heads/refactor/the-great-cms-migration'
    concurrency:
      group: site-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node and PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        working-directory: site
        run: pnpm install
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: search
          path: ./site
      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SANITY_WEBHOOK_SECRET: ${{ secrets.SANITY_WEBHOOK_SECRET }}
          envkey_GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Deploy Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CROS_STAGING }}'
          # Change to live when merged
          channelId: next
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
